# Generated by Django 4.2.3 on 2023-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_answer_offer_delete_peer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='index',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='index',
            field=models.TextField(),
        ),
    ]
