# Generated by Django 4.2.3 on 2023-07-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_alter_answer_index_alter_offer_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='offer',
            new_name='answer',
        ),
    ]
