# Generated by Django 4.2.3 on 2023-07-28 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_answer_host_uuid_offer_host_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='active_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
